[project]
name = "github-user-activity"
version = "0.1.0"
description = "CLI tool to fetch and show GitHub user activity"
authors = [{ name = "Danil Yudin", email = "dayudin78@gmail.com" }]
dependencies = []

[project.scripts]
github-activity = "github_activity.cli:main"
